Add Default Image
csci-499-sp23/team-2-sp23 pull request #167
Opened 2023-04-07 23:31 UTC by manav809

2023-04-07 23:32 UTC, Remos96 submitted a review, later dismissed
Looks good but add description to PR

2023-04-07 23:34 UTC, JoshuaRamc commented
Add description to PR, and also check with Devin if we want to leave comments in code

2023-04-07 23:41 UTC, JoshuaRamc commented
Also I would say do not put the image as a link, rather add it the same way we added the budget eats logo

2023-04-07 23:41 UTC, DLi7077 requested changes
Please format your code before commiting

2023-04-07 23:41 UTC, DLi7077 commented on client/src/pages/Search/GridView/RestaurantCard/ImageCard.js
> +  alt={src}
alt should describe the image for screen readers, like "restaurant" or "dolphin eating cheese"

2023-04-07 23:41 UTC, DLi7077 commented on client/src/pages/Search/GridView/RestaurantCard/ImageCard.js
> +    currentTarget.src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80";
Not a fan of how this was implemented.
You could just have something like:
```jsx
src = { restaurant_image ?? fallback_image }
```
Ask @JoshuaRamc about value coalescing 

Also, don't like how the default picture is a colorful chicken salad. Doesn't give the impression that the restaurant has no image. Use a bland image like this instead:
![image](https://user-images.githubusercontent.com/51217000/230692533-1b657ec9-1a95-42a6-98f0-673dbc35ae85.png)

2023-04-07 23:41 UTC, Remos96 commented on client/src/pages/Search/GridView/RestaurantCard/ImageCard.js
> +    currentTarget.src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80";
Remove link, download the image

2023-04-07 23:43 UTC, DLi7077 commented on client/src/pages/Search/GridView/RestaurantCard/ImageCard.js
> +    currentTarget.src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80";
using nullish coalescing lets you remove that `onError` prop

2023-04-07 23:46 UTC, DLi7077 commented on client/src/pages/Search/GridView/RestaurantCard/ImageCard.js
> +    currentTarget.src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80";
hint: This file should only have 2 line changes

import defaultImage
nullish coalesce on image url

2023-04-08 00:30 UTC, DLi7077 requested changes
One last change.
Squash your changes and we're good to go

2023-04-08 00:30 UTC, DLi7077 commented on client/src/pages/Search/GridView/RestaurantCard/ImageCard.js
> +import default_restaurant_img from "../../../../assets/images/default-restaurant-img.png";
Nit use camelCase

2023-04-08 00:42 UTC, manav809 commented
> One last change. Squash your changes and we're good to go

I squashed

2023-04-08 00:45 UTC, DLi7077 approved these changes

2023-04-08 00:45 UTC, merged

2023-04-08 00:45 UTC, JoshuaRamc approved these changes
coalesce operator logic looks good