Add User Location and Fill Address Bar
csci-499-sp23/team-2-sp23 pull request #313
Opened 2023-05-11 04:39 UTC by manav809

<img width="430" alt="Screen Shot 2023-05-11 at 12 39 12 AM" src="https://github.com/csci-499-sp23/team-2-sp23/assets/73366731/0b9d8baf-a995-4c16-b91c-c3597cca733b">

2023-05-11 04:56 UTC, DLi7077 requested changes

2023-05-11 04:56 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +    const reversegeolocate = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=${process.env.REACT_APP_GOOGLE_API_KEY}`;
dont do this. This exposes our api key.
![image](https://github.com/csci-499-sp23/team-2-sp23/assets/51217000/6c4ba593-9f11-4478-aac7-8bcd07895b8b)

2023-05-11 04:56 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +  const [address, setAddress] = useState(HUNTER_COLLEGE_ADDRESS);
using state causes the address value to be stuck at whatever the address is

2023-05-11 04:56 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      setAddress(response.data.results[0].formatted_address);
use googlePlacesRef instead (2 lines under)

Read the docs to see how to use refs
https://react.dev/reference/react/useRef

2023-05-11 04:56 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +        value={address}
dont need these, because useState is not the way to go here.

2023-05-11 04:56 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
>  export default function AddressSearch({ updateFields }) {
pass the updateQuerySearch function down here so we can reflect the address changes

2023-05-11 04:56 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +    const coordinates = await getUserCoordinates();
missing `catch`. What if the user decides to refuse read location permissions?

2023-05-11 04:59 UTC, DLi7077 requested changes

2023-05-11 04:59 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +  async function handleClick() {
function name sucks balls

2023-05-11 05:00 UTC, manav809 commented on client/src/pages/Search/AddressSearch.js
> +  async function handleClick() {
lmao

2023-05-11 05:22 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +    const reversegeolocate = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=${process.env.REACT_APP_GOOGLE_API_KEY}`;
ways we can resolve this:

1. Leave it, but restrict permissions based on domain and ip address
2. Let the server handle address match query

2023-05-11 05:58 UTC, DLi7077 requested changes
Please get into the habit of formatting your code

2023-05-11 05:58 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      </IconButton>
put this as a startAdornment (see line 51 - 64)

2023-05-11 05:58 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +        googlePlacesRef.current.value = address;
how are you accessing a variable before declaration? googlePlacesRef was declared on line 26 and you're using it on line 19

2023-05-11 05:58 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      axios.get(reversegeolocate).then(function (response) {
this should be a function in the api folder

2023-05-11 05:58 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +        const address = response.data.results[0].formatted_address;
add a comment here explaining why index 0

2023-05-11 05:58 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      const reversegeolocate = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=${process.env.REACT_APP_GOOGLE_API_KEY}`;
`reversegeolocate` <- Make this camelCase, also inaccurate variable name

2023-05-11 05:58 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      alert("Please Enable Location Services")
I can tell you didnt format your code because there's a missing semicolon

2023-05-12 17:49 UTC, DLi7077 requested changes

2023-05-12 17:49 UTC, DLi7077 commented on client/src/api/location-api.js
> +      console.log(address);
missing return

2023-05-12 17:49 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      });
Use the location-api function you made instead

2023-05-12 17:49 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      // googlePlacesRef.current.value = address;
remove commented code

2023-05-12 17:49 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      </IconButton>
This should be an endAdornment or startAdornment. See InputProps of the TextField right above this.

2023-05-12 17:49 UTC, DLi7077 commented on client/src/api/location-api.js
> +      const address = response.data.results[0].formatted_address;
document why index 0, in case in the future we have to refactor this. It's not immediately obvious why the first one is picked

2023-05-12 17:49 UTC, DLi7077 commented on client/src/api/location-api.js
> +    const addressObj = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=${process.env.REACT_APP_GOOGLE_API_KEY}`;
a better variable name for this would be: "reverseGeocodeURL"

2023-05-12 20:06 UTC, DLi7077 requested changes

2023-05-12 20:06 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +  async function userAddress({ updateFields }) {
`updateToUserAddress` would be a better name for this function

2023-05-12 20:07 UTC, DLi7077 requested changes

2023-05-12 20:07 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +      </IconButton>
This should be an endAdornment or startAdornment. See InputProps of the TextField right above this.

2023-05-12 20:31 UTC, DLi7077 requested changes

2023-05-12 20:31 UTC, DLi7077 commented on client/src/pages/Search/AddressSearch.js
> +  async function updateToUserAddress({ updateFields }) {
nit: new line before function definition

2023-05-12 20:34 UTC, DLi7077 approved these changes
lgtm

2023-05-12 20:34 UTC, merged