Add food price sort to restaurant page
csci-499-sp23/team-2-sp23 pull request #329
Opened 2023-05-15 03:24 UTC by JoshuaRamc

Added a toggler that changes the way in which foods are sorted on the restaurant page by price. Default sort is by low-to-high price.

2023-05-15 04:35 UTC, DLi7077 requested changes

2023-05-15 04:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +      </FormControl>
This should be in its own component.

Using menu items feels too bloated. Can you think of a cleaner UI?

2023-05-15 06:29 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +      </FormControl>
What I mean is that this is taking too much space
![image](https://github.com/csci-499-sp23/team-2-sp23/assets/51217000/a889136f-16f7-4582-be94-2fc7fc843ddc)

2023-05-15 06:30 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +      <FormControl sx={{ m: 1, maxWidth: 140, minWidth: 100 }}>
why the min max width?

2023-05-15 06:30 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +        <InputLabel id="demo-simple-select-helper-label">Price Sort</InputLabel>
why this id?

2023-05-15 06:35 UTC, DLi7077 requested changes

2023-05-15 06:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +          onChange={handleSortChange}
if you really to use select, use the "standard" variant. See how I did our restaurant sorts

2023-05-15 06:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +  const [sortDirection, setSortDirection] = useState("");
default this to ascending price

2023-05-15 06:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +          <MenuItem value={-1}>High-To-Low</MenuItem>
just label these "Ascending" and "Descending"

2023-05-15 06:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +      <FormControl sx={{ m: 1, maxWidth: 140, minWidth: 100 }}>
why the min & max width?

2023-05-15 06:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +        <InputLabel id="demo-simple-select-helper-label">Price Sort</InputLabel>
why this id?

2023-05-15 06:35 UTC, DLi7077 commented on client/src/pages/Restaurant/RestaurantView/index.js
> +          id="food Sorter"
ids are good for testing. If you're gonna write tests, add these ids when you're making the tests instead

2023-05-16 03:32 UTC, JoshuaRamc commented
Updated UI for the sort button: {changes on click from downwards to upwards arrow} 
![image](https://github.com/csci-499-sp23/team-2-sp23/assets/112503024/8cfc1959-0491-4dd4-9a9d-e6186da65c44)

2023-05-16 03:50 UTC, DLi7077 commented
looks aight

2023-05-16 04:05 UTC, DLi7077 approved these changes
good work

2023-05-16 04:06 UTC, merged